### ISSUE TITLE
Infinite loop at combostrap.com/pageimage

### ISSUE THREAD

**Issue by atnbueno** [ComboStrap/website#4]
The URL keeps growing and growing... 😬

**Comment by gerardnico** [comment]
Yo. Thanks for the report.
I corrected it.

Where did you get this link?
The correct link is:
https://combostrap.com/page-image

Combostrap was doing a redirect to the search engine.
And unfortunately, there was a bug in the link rewrite that was deleting the search action (do parameter)

The correction:
https://github.com/ComboStrap/combo/commit/078e2b46f4b6c58a239f1237fae0955ca1b86c27

You can update it to the latest version by following this page
https://combostrap.com/release/how-to-update-combo-or-a-third-party-plugin-in65c0ya
(Unfortunately, Combostrap cannot be updated via update anymore because of the DokuWiki way of updating.)

**Comment by atnbueno** [comment]
> Where did you get this link? The correct link is: https://combostrap.com/page-image

It came up in a bottom right popup about "not having a main image". I haven't been able to reproduce it.

**Comment by atnbueno** [comment]
Correction: I was able to reproduce it just by going to a non existing page when logged out 😬

I've updated `lib/plugins/combo/ComboStrap/Web/UrlRewrite.php` manually and the issue has been solved 👍🏼

**Comment by gerardnico** [comment]
A weird bug that I would never have seen. 
Thanks for your professional look.
