### ISSUE TITLE
Updates suggested for "Get Started"

### ISSUE THREAD

**Issue by atnbueno** [ComboStrap/website#5]
Some updates suggested for the "Get Started" section in the website:

<https://combostrap.com/get-started/how-to-install-dokuwiki-h52gxusb>

❌ DokuWiki version: Release 2020-07-29 "Hogfather"
✔ DokuWiki version: Release 2023-04-04a "Jack Jackrum"

❌ php version supported: 7.4 to 8.2
✔ php version supported: 8.1 to 8.2 *(because 8.0 is already EOL)*

<https://combostrap.com/support/combostrap-platform-requirements-956axulc#php>

❌ unbuntu 8.1
✔ ubuntu with php 8.2

❌ php-gd2
✔ php-gd

❌ php-openssl
✔ *nothing (included in PHP core)*

❌ *no mention if any "Popular Plugins" should be selected when downloading DokuWiki*
✔ *recommend what to select (including selecting only desired languages)*

<https://combostrap.com/get-started/third-plugins-combostrap-getting-started-luf5ymxq>

❌ *recommends installing plugins **after** installing **Combo**
✔ *I would mention here that **Combo** has to be disabled before installing any other plugin (and re-enabled later)*

Currently it seems only to be mentioned in the "When updating..." page:
<https://combostrap.com/release/how-to-update-combo-or-a-third-party-plugin-in65c0ya#how_to_update_a_third_plugin_such_as_sqlite>

**Comment by gerardnico** [comment]
Thanks. I have made the changes as requested.
https://github.com/ComboStrap/website/commit/070b1a33b25533b792812c301413fc0eaacab982
https://github.com/ComboStrap/website/commit/1887833698aa89b7cc9bce2259c43053d75bb460

For me, it was always php-gd2 and not php-gd because gd2 is the new version of the old gd.

For plugin installation, you can install them. The problem occurs only when you want to update them
because Dokuwiki will browse the whole directory and keep in memory the listing of the files.

Recommended plugins are in the highlight section. May be the name is not the best. Open for suggestions.
https://combostrap.com/get-started/third-plugins-combostrap-getting-started-luf5ymxq#highlights

**Comment by gerardnico** [comment]
I'm closing but open it as you want ... :) Need to work on my auto-close bot.

**Comment by atnbueno** [comment]
- I'm using Ubuntu 22.04.03 LTS and PHP 8.2.13
- The command `apt search php-gd` finds "GD module for PHP"
- The command `apt search php-gd2` doesn't find anything
